### ISSUE TITLE
TypeError in tutorial

### ISSUE THREAD

**Issue by ExoRob** [christinahedges/contaminante#3]
Hi,

I have been trying to run your tutorial on my computer:

```
import contaminante
import matplotlib.pyplot as plt

fig, result = contaminante.calculate_contamination(targetid='KIC {}'.format(6804648),
                               period=0.700606,
                               t0=131.59767,
                               duration=0.993/24,
                               mission='kepler')
plt.show()
```

but get the following error:

```
Modeling TPFs:   0%|                                                                   | 0/18 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "check-contamination.py", line 8, in <module>
    mission='kepler')
  File "/Users/robertwells/anaconda3/envs/contaminante/lib/python3.6/site-packages/contaminante/contaminante.py", line 86, in calculate_contamination
    clc = build_lc(tpf, aper, background=background, cadence_mask=t_mask, spline_period=2)
  File "/Users/robertwells/anaconda3/envs/contaminante/lib/python3.6/site-packages/contaminante/utils.py", line 306, in build_lc
    SA = build_X(tpf, np.ones(len(tpf.time)), cbvs=cbvs, spline=spline, background=background, spline_period=spline_period)
  File "/Users/robertwells/anaconda3/envs/contaminante/lib/python3.6/site-packages/contaminante/utils.py", line 123, in build_X
    spline_dm = lk.correctors.designmatrix.create_spline_matrix(tpf.time, n_knots=np.max([4, int((tpf.time[-1] - tpf.time[0])//spline_period)])).values
TypeError: unsupported operand type(s) for //: 'TimeDelta' and 'int'
```

How can I resolve this?

I have astropy 4.1rc1 the Github master version of lightkurve.

**Comment by christinahedges** [comment]
Hey Rob! I'm sorry I didn't see this earlier, I am just about to push a new version of contaminante, and this should resolve your error.

The reason that there is an error is because `lightkurve` changed their API right around the time I built `contaminante`, and so it broke in an ugly way in a lot of places. The new update should fix this

Sorry for the slow reply!

**Comment by christinahedges** [comment]
Hi @ExoRob, the new version is all merged in, you should be able to either pull from master or `pip install -U contaminante`, which should give you version 0.5.2

If you get stuck again do let me know and I'll try to be faster on the reply!

C
